version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dns_health
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dns_health"]
      interval: 10s
      timeout: 5s
      retries: 5

  zonemaster_backend:
    image: zonemaster/backend:latest
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - DATABASE_URL=postgresql+asyncpg://user:password@db/dns_health
      - DATABASE_URL_SYNC=postgresql://user:password@db/dns_health
      - ZONEMASTER_API_URL=http://zonemaster_backend:8080/RPC2
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      zonemaster_backend:
        condition: service_healthy
    command: >
      sh -c "
        uv run alembic upgrade head &&
        uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data:
