"""Create DNS check and result tables

Revision ID: 001
Revises: 
Create Date: 2024-12-25 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dns_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_checks_domain'), 'dns_checks', ['domain'], unique=False)
    op.create_index(op.f('ix_dns_checks_id'), 'dns_checks', ['id'], unique=False)
    op.create_table('dns_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dns_check_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dns_check_id'], ['dns_checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_results_dns_check_id'), 'dns_results', ['dns_check_id'], unique=False)
    op.create_index(op.f('ix_dns_results_id'), 'dns_results', ['id'], unique=False)
    op.create_index(op.f('ix_dns_results_level'), 'dns_results', ['level'], unique=False)
    op.create_index(op.f('ix_dns_results_module'), 'dns_results', ['module'], unique=False)
    op.create_index(op.f('ix_dns_results_tag'), 'dns_results', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dns_results_tag'), table_name='dns_results')
    op.drop_index(op.f('ix_dns_results_module'), table_name='dns_results')
    op.drop_index(op.f('ix_dns_results_level'), table_name='dns_results')
    op.drop_index(op.f('ix_dns_results_id'), table_name='dns_results')
    op.drop_index(op.f('ix_dns_results_dns_check_id'), table_name='dns_results')
    op.drop_table('dns_results')
    op.drop_index(op.f('ix_dns_checks_id'), table_name='dns_checks')
    op.drop_index(op.f('ix_dns_checks_domain'), table_name='dns_checks')
    op.drop_table('dns_checks')
    # ### end Alembic commands ###